name: manual
on:
        workflow_dispatch:
            inputs:
                name:
                    description: 'Nombre del usuario'
                    required: true
                    default: 'GitHub Actions'
jobs:
    manual:
        runs-on: ubuntu-24.04
        steps:
            - name: Saludo
                env:
                    LOG_LEVEL:${{ inputs.logging_level }}
                    ENVIRONMENT:${{ inputs.ENVIRONMENT }}
                    DRY_RUN: ${{ inputs.dry_run }}
                    REASON: ${{ inputs.REASON}}